name: tcm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - notebook
  - jupyter-collaboration
  - ipywidgets
  - pip
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.4
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anthropic==0.52.1
      - asgiref==3.8.1
      - backoff==2.2.1
      - bcrypt==4.3.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - chromadb==1.0.11
      - click==8.2.1
      - code-splitter==0.1.5
      - coloredlogs==15.0.1
      - dataclasses-json==0.6.7
      - deprecated==1.2.18
      - distro==1.9.0
      - dnspython==2.7.0
      - durationpy==0.10
      - fastapi==0.115.9
      - filelock==3.18.0
      - filetype==1.2.0
      - flatbuffers==25.2.10
      - frozenlist==1.6.0
      - fsspec==2025.5.1
      - google-ai-generativelanguage==0.6.18
      - google-api-core==2.24.2
      - google-auth==2.40.2
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.2
      - grpcio==1.73.0rc1
      - grpcio-status==1.71.0
      - hf-xet==1.1.2
      - httptools==0.6.4
      - httpx-sse==0.4.0
      - huggingface-hub==0.32.2
      - humanfriendly==10.0
      - importlib-metadata==8.6.1
      - jiter==0.10.0
      - joblib==1.5.1
      - jq==1.8.0
      - jsonpatch==1.33
      - kubernetes==32.0.1
      - langchain==0.3.25
      - langchain-anthropic==0.3.14
      - langchain-chroma==0.2.4
      - langchain-community==0.3.24
      - langchain-core==0.3.62
      - langchain-google-genai==2.1.5
      - langchain-huggingface==0.2.0
      - langchain-mongodb==0.6.2
      - langchain-openai==0.3.18
      - langchain-text-splitters==0.3.8
      - langgraph==0.4.7
      - langgraph-checkpoint==2.0.26
      - langgraph-prebuilt==0.2.2
      - langgraph-sdk==0.1.70
      - langsmith==0.3.43
      - lark==1.2.2
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - mmh3==5.1.0
      - mpmath==1.3.0
      - multidict==6.4.4
      - mypy-extensions==1.1.0
      - networkx==3.5
      - numpy==2.2.6
      - oauthlib==3.2.2
      - onnxruntime==1.22.0
      - openai==1.82.0
      - opentelemetry-api==1.33.1
      - opentelemetry-exporter-otlp-proto-common==1.33.1
      - opentelemetry-exporter-otlp-proto-grpc==1.33.1
      - opentelemetry-instrumentation==0.54b1
      - opentelemetry-instrumentation-asgi==0.54b1
      - opentelemetry-instrumentation-fastapi==0.54b1
      - opentelemetry-proto==1.33.1
      - opentelemetry-sdk==1.33.1
      - opentelemetry-semantic-conventions==0.54b1
      - opentelemetry-util-http==0.54b1
      - orjson==3.10.18
      - ormsgpack==1.10.0
      - packaging==24.2
      - pillow==11.2.1
      - pipdeptree==2.26.1
      - posthog==4.2.0
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - pymongo==4.13.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - python-dotenv==1.1.0
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sentence-transformers==4.1.0
      - shellingham==1.5.4
      - sqlalchemy==2.0.41
      - starlette==0.45.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.7.0
      - tqdm==4.67.1
      - transformers==4.52.4
      - typer==0.16.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - uvicorn==0.34.2
      - uvloop==0.21.0
      - watchfiles==1.0.5
      - websockets==15.0.1
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.20.0
# You may need to change this
# prefix: /Users/username/miniconda/envs/rag_restore
